name: Deploy Static Site to Azure App Service

on:
  push:
    branches:
      - main  # Change if your default branch is master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # No npm install — just upload the files
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: YOUR_APP_SERVICE_NAME   # e.g. my-static-site
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
